#spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: ${DB_URL:jdbc:h2:mem:user}
#    username: ${DB_USERNAME:admin}
#    password: ${DB_PASSWORD:}
#    h2:
#      console:
#        enable: true
#
#  jpa:
#    properties:
#      hibernate:
#        format_sql: true
#        show_sql: true
#        dialect: org.hibernate.dialect.H2Dialect
#        hbm2ddl:
#          auto: create
#    hibernate:
#      ddl-auto: create
#    generate-ddl: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#    show-sql: false



#    hibernate:
#      ddl-auto: create
#    generate-ddl: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#    show-sql: false
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;
    username: admin
    password:
    h2:
      console:
        enable: true

  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect